# Style Sederhana
SPAWN_JOIN: true
ESSENTIAL_SPAWN_LOCATION: 0,0,0,0
PREFIX: "&e&lHUB &d/ "
PLAYER_JOIN: "&2&l+ &6%player%"
PLAYER_QUIT: "&4&l- &6%player%"

# Database: MySQL
mysql:
  host: pej4bt4
  port: 3306
  database: KaHub
  username: sef0ngdu1t
  password: n4g4r4

# Command Messages
commands:
  all:
    - "&e└ /kahub reload &f- &7Reload the plugin"
    - "&e└ /fly &f- &7Toggle flight mode (&b&lMVP &for above&7)"
    - "&e└ /spawn &f- &7Teleport to spawn"
    - "&e└ /clearinv [player] &f- &7Clear inventory (optional: specify player)"
    - "&e└ /gamemode <mode> &f- &7Change gamemode"
    - "&e└ /setspawn &f- &7Set the server spawn location"
  player:
    - "&e└ /fly &f- &7Toggle flight mode"
    - "&e└ /spawn &f- &7Teleport to spawn"
  staff:
    - "&e└ /kahub reload &f- &7Reload the plugin"
    - "&e└ /clearinv [player] &f- &7Clear inventory (optional: specify player)"
    - "&e└ /gamemode <mode> &f- &7Change gamemode"

# Filter Manager
anti_swear:
  enabled: true
  blocked_words:
    - fuck
    - shit
    - bitch
    - kontol
    - anjing
    - bangsat
    - bangsad
    - ngentot
    - babi
    - tai
    - pepek
    - memek
    - porn
    - lonte
    - yatim
    - dajjal

